name: ci/cd

on: 
    push:

jobs:
    lint-and-test:
       uses: ./.github/workflows/lint.yml

         
    build:
    
      secrets: inherit
      uses: ./.github/workflows/build.yml

    deploy: 
      
      needs: build  
      uses: ./.github/workflows/deploy.yml

