name: linting 

on:
    push:
jobs:
    lint:
        runs-on: ubuntu:latest
        steps:
            - name: code
              uses: actions/checkout@v7  

            - name: install dependancis
              run: npm install --save-dev eslint
            
            - name: initialize it
              run: npx eslint --init
            - name: run 
              run: npx eslint .    


